name: build-docker-image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: "guo_wang_113@163.com"
        password: "wangguo@1131023"

    - name: Build base image
      run: bash scripts/build-base-image.sh

    - name: Build nginx image
      run: bash scripts/build-nginx.sh

    - name: Build standalone image
      run: bash scripts/build-standalone.sh

    - name: Build static image
      run: bash scripts/build-static.sh

    - name: Push images to Docker Hub
      run: bash scripts/push-images.sh
